USE SQL_INVOICING;

SELECT 
P.client_id as CLIENT_ID,
C.NAME, 
P.DATE AS PAYMENT_DATE,
P.AMOUNT as AMOUNT,
PYM.NAME AS PAYMENT_METHODE
FROM CLIENTS C 
JOIN INVOICES I ON C.CLIENT_ID = I.CLIENT_ID 
JOIN PAYMENTS P ON C.CLIENT_ID = P.CLIENT_ID
JOIN payment_methods PYM ON P.PAYMENT_ID = P.PAYMENT_ID;