USE SQL_STORE;
SELECT O.ORDER_ID,
O.ORDER_DATE,
C.FIRST_NAME,
OS.NAME as STATUS_OF_ORDER
 FROM ORDERS O 
JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN order_statuses OS ON O.STATUS = OS.order_status_id;


SELECT * FROM order_statuses