USE SQL_STORE;
SELECT * FROM PRODUCTS;
SELECT O.PRODUCT_ID, `QUANTITY` FROM ORDER_ITEMS O
JOIN PRODUCTS P
ON P.PRODUCT_ID = O.PRODUCT_ID ;

SELECT * FROM PRODUCTS;
SELECT O.PRODUCT_ID, `QUANTITY` FROM ORDER_ITEMS O
LEFT JOIN PRODUCTS P
ON P.PRODUCT_ID = O.PRODUCT_ID ;

SELECT * FROM ORDER_ITEMS O
LEFT JOIN PRODUCTS P
ON P.PRODUCT_ID = O.PRODUCT_ID WHERE `QUANTITY_IN_STOCK` > 40 and P.NAME REGEXP 'ATE$';


